version: '3.1'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - some-net
  opencart:
    image: 'docker.io/bitnami/opencart:3-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    expose:
      - "80"
    environment:
      - OPENCART_HOST=localhost
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    privileged: true
    depends_on:
      - mariadb
    networks:
      - some-net
  test:
    #command: pytest --url_base http:127.0.0.1
    command: python -m pytest --browser chrome --url_base http://172.22.0.1 tests
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - opencart
      - mariadb
    networks:
      - some-net
    privileged: true
    links:
      - opencart
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local

networks:
  some-net:
    driver: bridge